server:
  port: 8080

spring:
  kafka:
    consumer:
      group-id: "my-secund-topic"
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      acks: all

tpd.messages-per-request: 10
