# See: https://github.com/cloudhut/kowl/tree/master/docs/config for reference config files.
kafka:
  brokers:
    - broker1:19092
    - broker2:19093
    - broker3:19094

# server:
  # listenPort: 8080