server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:orderdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all

