version: '3'
services:

#  mariadb:
#    image: mariadb:10.3
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_DATABASE: s2m_catalog_multicloud
#      MYSQL_ROOT_PASSWORD: root
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

#  prom:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./tmp/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - host

#networks:
#  host:

  zookeeper:
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
      - "2888"

  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_CREATE_TOPICS: "logs:1:1,events:1:1,events-mirror:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

#  jaeger:
#    image: jaegertracing/all-in-one:1.8
#    ports:
#      - "5775:5775/udp"
#      - "6831:6831/udp"
#      - "6832:6832/udp"
#      - "5778:5778"
#      - "16686:16686"
#      - "14268:14268"
#      - "9411:9411"
#    environment:
#      COLLECTOR_ZIPKIN_HTTP_PORT: 9411